services:
  app:
    image: "mcr.microsoft.com/devcontainers/python:1-3.12-bullseye"
   
    volumes:
      - ../..:/workspaces:cached    
    command: sleep infinity

  qdrant:
    image: qdrant/qdrant:v1.14.0
    ports:
      - 6333:6333
    volumes:
      - qdrant-storage:/qdrant/storage

volumes:
  qdrant-storage:
    